url: https://phothin.dev
# site
source: app
sass:
  style: compressed
plugins:
  - jekyll-minifier
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Makefile
jekyll-minifier:
  compress_css: false
collections:
  pages:
    output: true
  notes:
    output: true
